/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.microlabs.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-29-2013
 * 
 * XDoclet definition:
 * @struts.form name="homeForm"
 */
public class HomeForm extends ActionForm {
	
	private String visName;
	private String visCompany;
	private String visDate;
	private String visPlace;
	private String toMeet;
	private String department;
	private String timeIn;
	private String timeOut;
	
	private String itemdesc;
	private String uom;
	private String qtyrcvd;
	private String timein;
	private String suppliername;

	private String qty;
	private String sentby;
	private String destination;
	
	public String getQty() {
		return qty;
	}
	public void setQty(String qty) {
		this.qty = qty;
	}
	public String getSentby() {
		return sentby;
	}
	public void setSentby(String sentby) {
		this.sentby = sentby;
	}
	public String getDestination() {
		return destination;
	}
	public void setDestination(String destination) {
		this.destination = destination;
	}
	public String getItemdesc() {
		return itemdesc;
	}
	public void setItemdesc(String itemdesc) {
		this.itemdesc = itemdesc;
	}
	public String getUom() {
		return uom;
	}
	public void setUom(String uom) {
		this.uom = uom;
	}
	public String getQtyrcvd() {
		return qtyrcvd;
	}
	public void setQtyrcvd(String qtyrcvd) {
		this.qtyrcvd = qtyrcvd;
	}
	public String getTimein() {
		return timein;
	}
	public void setTimein(String timein) {
		this.timein = timein;
	}
	public String getSuppliername() {
		return suppliername;
	}
	public void setSuppliername(String suppliername) {
		this.suppliername = suppliername;
	}
	public String getVisName() {
		return visName;
	}
	public void setVisName(String visName) {
		this.visName = visName;
	}
	public String getVisCompany() {
		return visCompany;
	}
	public void setVisCompany(String visCompany) {
		this.visCompany = visCompany;
	}
	public String getVisDate() {
		return visDate;
	}
	public void setVisDate(String visDate) {
		this.visDate = visDate;
	}
	public String getVisPlace() {
		return visPlace;
	}
	public void setVisPlace(String visPlace) {
		this.visPlace = visPlace;
	}
	public String getToMeet() {
		return toMeet;
	}
	public void setToMeet(String toMeet) {
		this.toMeet = toMeet;
	}
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	public String getTimeIn() {
		return timeIn;
	}
	public void setTimeIn(String timeIn) {
		this.timeIn = timeIn;
	}
	public String getTimeOut() {
		return timeOut;
	}
	public void setTimeOut(String timeOut) {
		this.timeOut = timeOut;
	}
	
	
	
	
}