/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.microlabs.form;
import java.util.ArrayList;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-21-2013
 * 
 * XDoclet definition:
 * @struts.form name="loginForm"
 */
public class LoginForm extends ActionForm {
	/*
	 * Generated fields
	 */

	private ArrayList ar1_id = new ArrayList();
	private ArrayList ar2_name = new ArrayList();
	
	
	/** password property */
	private String password;

	/** gateno property */
	private String gateno;

	/** username property */
	private String username;

	/** location property */
	private String location;
	
	private String message;
	
	/*
	 * Generated Methods
	 */

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/** 
	 * Returns the gateno.
	 * @return String
	 */
	public String getGateno() {
		return gateno;
	}

	/** 
	 * Set the gateno.
	 * @param gateno The gateno to set
	 */
	public void setGateno(String gateno) {
		this.gateno = gateno;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the location.
	 * @return String
	 */
	public String getLocation() {
		return location;
	}

	/** 
	 * Set the location.
	 * @param location The location to set
	 */
	public void setLocation(String location) {
		this.location = location;
	}

	public ArrayList getAr1_id() {
		return ar1_id;
	}

	public void setAr1_id(ArrayList ar1_id) {
		this.ar1_id = ar1_id;
	}

	public ArrayList getAr2_name() {
		return ar2_name;
	}

	public void setAr2_name(ArrayList ar2_name) {
		this.ar2_name = ar2_name;
	}

}