/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.microlabs.form;

import java.util.ArrayList;

import org.apache.struts.action.ActionForm;

import com.microlabs.utils.IdValuePair;

/** 
 * MyEclipse Struts
 * Creation date: 02-08-2013
 * 
 * XDoclet definition:
 * @struts.form name="matinwardForm"
 */
public class MatinwardForm extends ActionForm {

	// ge_matinward_master fields
	private String mandt;
	private String finyear;
	private String locationid;
	private String gateno;
	private String gino;
	private String gidate;
	private String timein;
	private String docno;
	private String docdate;
	private String suppliername;
	private String supplierplace;
	private String vehicleno;
	private String drivername;
	private String transportername;
	private String enteredby;
	private String reasonremarks;
	private String potype;
	private String pono;
	private String podate;
	
	// ge_matinward_details fields
	private String itemno;
	private String[] matid;
	private String itemcode;
	private String itemdesc;
	private String uom;
	private String noofcases;
	private String qty;
	private String qtyrcvd;
	
	private String message;
	
	private ArrayList<IdValuePair> matlist;
	
	
	public ArrayList<IdValuePair> getMatlist() {
		return matlist;
	}
	public void setMatlist(ArrayList<IdValuePair> matlist) {
		this.matlist = matlist;
	}
	// getters and setters

	
	public String getMandt() {
		return mandt;
	}
	public void setMandt(String mandt) {
		this.mandt = mandt;
	}
	public String getFinyear() {
		return finyear;
	}
	public void setFinyear(String finyear) {
		this.finyear = finyear;
	}
	public String getLocationid() {
		return locationid;
	}
	public void setLocationid(String locationid) {
		this.locationid = locationid;
	}
	public String getGateno() {
		return gateno;
	}
	public void setGateno(String gateno) {
		this.gateno = gateno;
	}
	public String getGino() {
		return gino;
	}
	public void setGino(String gino) {
		this.gino = gino;
	}
	public String getGidate() {
		return gidate;
	}
	public void setGidate(String gidate) {
		this.gidate = gidate;
	}
	public String getTimein() {
		return timein;
	}
	public void setTimein(String timein) {
		this.timein = timein;
	}
	public String getDocno() {
		return docno;
	}
	public void setDocno(String docno) {
		this.docno = docno;
	}
	public String getDocdate() {
		return docdate;
	}
	public void setDocdate(String docdate) {
		this.docdate = docdate;
	}
	public String getSuppliername() {
		return suppliername;
	}
	public void setSuppliername(String suppliername) {
		this.suppliername = suppliername;
	}
	public String getSupplierplace() {
		return supplierplace;
	}
	public void setSupplierplace(String supplierplace) {
		this.supplierplace = supplierplace;
	}
	public String getVehicleno() {
		return vehicleno;
	}
	public void setVehicleno(String vehicleno) {
		this.vehicleno = vehicleno;
	}
	public String getDrivername() {
		return drivername;
	}
	public void setDrivername(String drivername) {
		this.drivername = drivername;
	}
	public String getTransportername() {
		return transportername;
	}
	public void setTransportername(String transportername) {
		this.transportername = transportername;
	}
	public String getEnteredby() {
		return enteredby;
	}
	public void setEnteredby(String enteredby) {
		this.enteredby = enteredby;
	}
	public String getReasonremarks() {
		return reasonremarks;
	}
	public void setReasonremarks(String reasonremarks) {
		this.reasonremarks = reasonremarks;
	}
	public String getPono() {
		return pono;
	}
	public void setPono(String pono) {
		this.pono = pono;
	}
	public String getPodate() {
		return podate;
	}
	public void setPodate(String podate) {
		this.podate = podate;
	}
	public String getItemno() {
		return itemno;
	}
	public void setItemno(String itemno) {
		this.itemno = itemno;
	}
	
	public String[] getMatid() {
		return matid;
	}
	public void setMatid(String[] matid) {
		this.matid = matid;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getItemcode() {
		return itemcode;
	}
	public void setItemcode(String itemcode) {
		this.itemcode = itemcode;
	}
	public String getItemdesc() {
		return itemdesc;
	}
	public void setItemdesc(String itemdesc) {
		this.itemdesc = itemdesc;
	}
	public String getUom() {
		return uom;
	}
	public void setUom(String uom) {
		this.uom = uom;
	}
	public String getNoofcases() {
		return noofcases;
	}
	public void setNoofcases(String noofcases) {
		this.noofcases = noofcases;
	}
	public String getQty() {
		return qty;
	}
	public void setQty(String qty) {
		this.qty = qty;
	}
	public String getQtyrcvd() {
		return qtyrcvd;
	}
	public void setQtyrcvd(String qtyrcvd) {
		this.qtyrcvd = qtyrcvd;
	}
	public String getPotype() {
		return potype;
	}
	public void setPotype(String potype) {
		this.potype = potype;
	}

	
	

}