/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.microlabs.form;

import java.util.ArrayList;

import org.apache.struts.action.ActionForm;

import com.microlabs.utils.IdValuePair;

/** 
 * MyEclipse Struts
 * Creation date: 01-30-2013
 * 
 * XDoclet definition:
 * @struts.form name="visitorsForm"
 */
public class VisitorsForm extends ActionForm {

		private String finYear;
		private String visType;
		private String visPurpose;
		private String visName;
		private String visCompany;
		private String visDate;
		private String address;
		private String visPlace;
		private String visContact;
		private String belongings;
		private int nopersons;
		private String personnames;
		private String toMeet;
		private String deptType;
		private String timeIn;
		private String timeOut;
		private int visitorno;
		private String visitorimage;
		
		private String visSearch;
		
		private ArrayList<IdValuePair> vistypelist;
		private ArrayList<IdValuePair> vispurposelist;
		private ArrayList<IdValuePair> deptlist;
		
		private ArrayList ary_deptid = new ArrayList();
		private ArrayList ary_deptname = new ArrayList();
		
		private ArrayList ary_visitors = new ArrayList();
				
		private String message;

		
		public String getVisitorimage() {
			return visitorimage;
		}
		public void setVisitorimage(String visitorimage) {
			this.visitorimage = visitorimage;
		}
		public int getNopersons() {
			return nopersons;
		}
		public void setNopersons(int nopersons) {
			this.nopersons = nopersons;
		}
		public String getPersonnames() {
			return personnames;
		}
		public void setPersonnames(String personnames) {
			this.personnames = personnames;
		}
		public int getVisitorno() {
			return visitorno;
		}
		public void setVisitorno(int visitorno) {
			this.visitorno = visitorno;
		}
		public String getVisSearch() {
			return visSearch;
		}
		public void setVisSearch(String visSearch) {
			this.visSearch = visSearch;
		}
		public ArrayList<IdValuePair> getDeptlist() {
			return deptlist;
		}
		public void setDeptlist(ArrayList<IdValuePair> deptlist) {
			this.deptlist = deptlist;
		}
		public ArrayList<IdValuePair> getVispurposelist() {
			return vispurposelist;
		}
		public void setVispurposelist(ArrayList<IdValuePair> vispurposelist) {
			this.vispurposelist = vispurposelist;
		}
		public ArrayList<IdValuePair> getVistypelist() {
			return vistypelist;
		}
		public void setVistypelist(ArrayList<IdValuePair> vistypelist) {
			this.vistypelist = vistypelist;
		}
		public ArrayList getAry_deptid() {
			return ary_deptid;
		}
		public void setAry_deptid(ArrayList ary_deptid) {
			this.ary_deptid = ary_deptid;
		}
		public ArrayList getAry_deptname() {
			return ary_deptname;
		}
		public void setAry_deptname(ArrayList ary_deptname) {
			this.ary_deptname = ary_deptname;
		}
		public String getMessage() {
			return message;
		}
		public void setMessage(String message) {
			this.message = message;
		}
		public String getFinYear() {
			return finYear;
		}
		public void setFinYear(String finYear) {
			this.finYear = finYear;
		}
		public String getVisType() {
			return visType;
		}
		public void setVisType(String visType) {
			this.visType = visType;
		}
		public String getVisPurpose() {
			return visPurpose;
		}
		public void setVisPurpose(String visPurpose) {
			this.visPurpose = visPurpose;
		}
		public String getVisName() {
			return visName;
		}
		public void setVisName(String visName) {
			this.visName = visName;
		}
		public String getVisCompany() {
			return visCompany;
		}
		public void setVisCompany(String visCompany) {
			this.visCompany = visCompany;
		}
		public String getVisDate() {
			return visDate;
		}
		public void setVisDate(String visDate) {
			this.visDate = visDate;
		}
		public String getAddress() {
			return address;
		}
		public void setAddress(String address) {
			this.address = address;
		}
		public String getVisPlace() {
			return visPlace;
		}
		public void setVisPlace(String visPlace) {
			this.visPlace = visPlace;
		}
		public String getVisContact() {
			return visContact;
		}
		public void setVisContact(String visContact) {
			this.visContact = visContact;
		}
		public String getBelongings() {
			return belongings;
		}
		public void setBelongings(String belongings) {
			this.belongings = belongings;
		}
		public String getToMeet() {
			return toMeet;
		}
		public void setToMeet(String toMeet) {
			this.toMeet = toMeet;
		}
		public String getDeptType() {
			return deptType;
		}
		public void setDeptType(String deptType) {
			this.deptType = deptType;
		}
		public String getTimeIn() {
			return timeIn;
		}
		public void setTimeIn(String timeIn) {
			this.timeIn = timeIn;
		}
		public String getTimeOut() {
			return timeOut;
		}
		public void setTimeOut(String timeOut) {
			this.timeOut = timeOut;
		}
		public ArrayList getAry_visitors() {
			return ary_visitors;
		}
		public void setAry_visitors(ArrayList ary_visitors) {
			this.ary_visitors = ary_visitors;
		}
		



}