/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.microlabs.action;


import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.ServletConfig;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.j2ee.servlets.BaseHttpServlet;
import net.sf.jasperreports.engine.export.*;
import net.sf.jasperreports.engine.xml.JRXmlLoader;



import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.microlabs.db.ConnectionFactory;
import com.microlabs.form.HomeForm;
import com.microlabs.form.VisitorsForm;
import com.microlabs.db.MatinwardDB;
import com.microlabs.utils.MicrolabsUtils;
import com.microlabs.db.OthmatoutDB;
import com.microlabs.utils.PieChart;
import com.microlabs.db.VisitorsDB;
import com.microlabs.utils.VisitorsDash;

import com.microlabs.form.HomeForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-29-2013
 * 
 * XDoclet definition:
 * @struts.action path="/home" name="homeForm" input="/jsp/home.jsp" parameter="method" scope="request" validate="true"
 * @struts.action-forward name="home" path="/jsp/home.jsp"
 */
public class HomeAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */

	
	public ActionForward home(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HomeForm homeForm = (HomeForm) form;// TODO Auto-generated method stub
		
		 HttpSession session = request.getSession();
		 String gateno = (String)session.getAttribute("GateNo");
		 String username = (String)session.getAttribute("UserName");
		 String location = (String)session.getAttribute("LocationName");
		 String locationid = (String)session.getAttribute("Locationid");
		
		// For Visitor Dashboard
		VisitorsDB vi=new VisitorsDB();
		ArrayList a1=vi.getVisitorsDateWise(locationid);
		request.setAttribute("disvisitors", a1);
		
		// For Material Inward
		MatinwardDB mi = new MatinwardDB();
		ArrayList m1 = mi.getMatinwardDateWise(locationid);
		request.setAttribute("dismatinward", m1);
		
		// For Other Material Outward
		OthmatoutDB mo = new OthmatoutDB();
		ArrayList m2 = mo.getOthmatoutDateWise(locationid);
		request.setAttribute("disothermatout", m2);

		// GRAPH CREATION AND DISPLAY
		String id= session.getId();

		PieChart chartCreator = new PieChart();      
		/** Create a PieDataSet* */    
		String realPath=getServlet().getServletContext().getRealPath("/graph");
		/** Define a file location to save this chart */   
		String fileLocation = realPath+"/"+id+".jpg"; 
		chartCreator.processgraphimage(fileLocation, location.substring(0,location.lastIndexOf("-")));
		
		return mapping.findForward("home");
	}
	
	
	public ActionForward home1(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HomeForm homeForm = (HomeForm) form;// TODO Auto-generated method stub
	 HttpSession session=request.getSession();
    
     ServletConfig ctx=getServlet().getServletConfig();
    
    String path="VisitorsDaily.jrxml";
	String pat3=ctx.getServletContext().getRealPath("/Reports/"+path);
	
	System.out.println("path of the JRXML File is *********************"+path);
	System.out.println("pat3 of the JRXML File is *********************"+pat3);
	try {
		Connection con=ConnectionFactory.getConnection();
		
		   JasperReport jasperReport = JasperCompileManager.compileReport(pat3);

		   String path2="VisitorsDaily.jasper";

		   String path1=ctx.getServletContext().getRealPath("Reports/"+path2);
			//String path5="app_id.jpg";
			Map parameters = new HashMap();
			
			//parameters.put("STUDENTNAME","locationid");
		     JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,new HashMap(),con);
		     session.setAttribute(BaseHttpServlet.DEFAULT_JASPER_PRINT_SESSION_ATTRIBUTE,jasperPrint);
		     
		     JasperExportManager.exportReportToPdfFile(jasperPrint,"VisitorsDaily.pdf");
		     
		     /*if(jasperPrint!=null){
		 		byte[] pdfsButes;
		 		
		 			pdfsButes = JasperExportManager.exportReportToPdf(jasperPrint);
		 		
		 		StringBuffer buf=new StringBuffer();
		 		ServletOutputStream out=response.getOutputStream();
		 		response.setHeader("Content-disposition", "attachment; filename=\"VisitorsDaily.pdf\"");
		 		response.setContentLength(pdfsButes.length);
		 		int t=pdfsButes.length;
		 		out.write(pdfsButes);
		 		out.close();
		 		
		     }*/
		  
	} catch (Exception e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	
	
	return mapping.findForward("home");
	}
	
}